# -*- coding: utf-8 -*-
"""separate_tepals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VphN1NEPXSalyZm5m6b4CnPF_cSBNPiy
"""

def separate_tepals(im):
  """
  Separates tepals in an image.
  """

"""Takes an image of a lily tepal slice that 
contains 3 individual tepals and a scale bar 
and removes the scale bar, and outputs three 
images, one for each tepal.

Parameters
----------
im : 2D array uint8
     image
     image of a lily bud slice that contains
     three tepals

Returns
-------
tepal1 : 2D array uint8
         image
         image containing the first tepal in 
         the lily bud slice

tepal2 : 2D array uint8
         image
         image containing the second tepal in 
         the lily bud slice

tepal3 : 2D array uint8
         image
         image containing the third tepal in 
         the lily bud slice
"""

def separate_tepals(im):
  
  # Remove scale bar and scale text
  im_c = closing(im, disk(4))

  # Ensure no data is lost in the closing step by enlarging im_c and performing boolean logic with original image to isolate tepals
  im_c_overlap = erode(im_c, disk(7))
  im_bool = img_as_bool(im)
  im_teps = np.invert(np.logical_and(np.invert(im_bool), np.invert(im_c_overlap)))

  # Label tepals
  label_teps, _ = scipylabel(np.invert(im_teps))

  # Isolate tepals
  tepals = []

  for tepal in regionprops(label_teps):
    crop = np.pad(tepal.image, np.round(0.05*len(tepal.image)).astype(int))
    tepals.append(crop)

  # Save tepals
  tepal1 = img_as_ubyte(tepals[0])
  tepal2 = img_as_ubyte(tepals[1])
  tepal3 = img_as_ubyte(tepals[2])

  return tepal1, tepal2, tepal3

"""
Example
-------
import numpy as np

from skimage.util import img_as_bool, img_as_ubyte
from skimage.morphology import erosion as erode
from skimage.morphology import closing
from skimage.morphology import disk

from scipy.ndimage import label as scipylabel

from skimage.measure import regionprops

from google.colab import drive    # Code required to access files in google drive

drive.mount('/content/drive', force_remount=True)   # Mount google drive in order to access files

im = img_as_ubyte(plt.imread('/content/drive/MyDrive/LilyData/lilymask.jpeg'))

# Separate the tepals

tepalA, tepalB, tepalC = separate_tepals(im)

"""